services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vulnweb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../html:/var/www/html
    command: >
      --default-authentication-plugin=mysql_native_password
      --secure-file-priv=/var/www/html
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 5
  apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../html:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=vulnuser
      - MYSQL_PASSWORD=vulnpass
      - MYSQL_DB=vulnweb
volumes:
  db_data: 